global:
  resolve_timeout: 5m

route:
  receiver: "email-alert"
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: "email-alert"
    email_configs:
      - to: "angel.reyes.676@my.csun.edu"
        from: "revature.weatheralerts@gmail.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "revature.weatheralerts@gmail.com"
        auth_password: "gveziyqoyqzgaqvf"
        require_tls: true
